<?php
include_once 'partial/head.php';
$api = "rzp_test_eTk38MV4pvq0dA";
session_start();
if (isset($_SESSION['user_email'])) {
    $email = $_SESSION['user_email'];
    $company = $_SESSION['company'];
    $t_name = "orders_" . $company;
    $t_name2 = "users_" . $company;
} else {
    echo "<script>alert('Login');
        window.location.assign('user_login.php');
        </script>";
}
if (isset($_GET['pay_ment'])) {
    $new_amount = mysqli_real_escape_string($con, $_GET['pay_ment']);
    $sql = "UPDATE  $t_name SET payment='done',wallet_pay_option='off' WHERE order_by='$email';";
    mysqli_query($con, $sql);
}
// =====================================================================================================
if (isset($_POST['add_money'])) {
    $add_amount = mysqli_real_escape_string($con, $_POST['pay_ment']);
    $sql1 = "SELECT * FROM $t_name2 WHERE user_email='$email';";
    $result = mysqli_query($con, $sql1);
    $row1 = mysqli_fetch_assoc($result);
    $old_amount = $row1['balance'];
    $new_amount = $old_amount + $add_amount;
    $sql = "UPDATE  $t_name2 SET balance='$new_amount' WHERE user_email='$email';";
    mysqli_query($con, $sql);
}
?>
<script>
    window.onload = function() {
        document.getElementsByName('data-buttontext').click();
    }
</script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<form action="user_dash.php" method="POST">
    <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="<?php echo $api; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys data-amount="<?php echo $new_amount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35. data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account data-id="<?php echo 'payment_' . rand(10, 100); ?>"//Replace with the order_id generated by you in the backend. data-buttontext="pay" data-name="<?php $company; ?>" data-description="Order Now" data-image="https://vast-sierra-59108.herokuapp.com/img/logo2.png" data-prefill.name="" data-prefill.email="<?php echo $email1 ?>" data-prefill.contact="" data-theme.color="#e57373">
    </script>
    <input type="hidden" custom="Hidden Element" name="hidden">
</form>



<script>
    $(document).ready(function() {
        $('.razorpay-payment-button').click();
    });
</script>
<style>
    .razorpay-payment-button {
        display: none;
    }
</style>